# Generated by Django 2.2.3 on 2019-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
