# Generated by Django 2.2.3 on 2019-07-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
